import { Body, Controller, Delete, Get, Injectable, Module, Param, Patch, Post, UseGuards } from '@nestjs/common';
import { InjectModel, MongooseModule } from '@nestjs/mongoose';
import { IsIn, IsOptional, IsString, MaxLength } from 'class-validator';
import { Model, Types } from 'mongoose';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

@Schema({ timestamps: true, collection: 'credentials' }) class Credential { @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true }) userId!: Types.ObjectId; @Prop({ required: true, maxlength: 150 }) name!: string; @Prop({ enum: ['Website', 'Banking', 'Social Media', 'Other'], required: true }) category!: string; @Prop({ required: true, default: Date.now }) lastUpdated!: Date; @Prop({ type: Object, required: true }) encryptedData!: Record<string, string>; }
const CredentialSchema = SchemaFactory.createForClass(Credential); CredentialSchema.index({ userId: 1, lastUpdated: -1 });
class CredentialDto { @IsString() @MaxLength(150) name!: string; @IsIn(['Website', 'Banking', 'Social Media', 'Other']) category!: string; @IsOptional() @IsString() lastUpdated?: string; @IsOptional() encryptedData?: Record<string, string>; }
@Injectable() class CredentialsService { constructor(@InjectModel(Credential.name) private readonly model: Model<Credential>) {} list(userId: string) { return this.model.find({ userId }).sort({ lastUpdated: -1 }).lean().exec(); } create(userId: string, dto: CredentialDto) { return this.model.create({ ...dto, userId, encryptedData: dto.encryptedData ?? {}, lastUpdated: dto.lastUpdated ? new Date(dto.lastUpdated) : new Date() }); } update(userId: string, id: string, dto: Partial<CredentialDto>) { const data = { ...dto, ...(dto.lastUpdated ? { lastUpdated: new Date(dto.lastUpdated) } : {}), ...(dto.encryptedData ? { encryptedData: dto.encryptedData } : {}) }; return this.model.findOneAndUpdate({ _id: id, userId }, data, { new: true, runValidators: true }).exec(); } remove(userId: string, id: string) { return this.model.deleteOne({ _id: id, userId }).exec(); } }
@Controller('credentials') @UseGuards(JwtAuthGuard) class CredentialsController { constructor(private readonly service: CredentialsService) {} @Get() list(@CurrentUser() user: { sub: string }) { return this.service.list(user.sub); } @Post() create(@CurrentUser() user: { sub: string }, @Body() dto: CredentialDto) { return this.service.create(user.sub, dto); } @Patch(':id') update(@CurrentUser() user: { sub: string }, @Param('id') id: string, @Body() dto: Partial<CredentialDto>) { return this.service.update(user.sub, id, dto); } @Delete(':id') remove(@CurrentUser() user: { sub: string }, @Param('id') id: string) { return this.service.remove(user.sub, id); } }
@Module({ imports: [MongooseModule.forFeature([{ name: Credential.name, schema: CredentialSchema }])], controllers: [CredentialsController], providers: [CredentialsService] }) export class CredentialsModule {}