import { Body, Controller, Delete, Get, Injectable, Module, Param, Patch, Post, UseGuards } from '@nestjs/common';
import { InjectModel, MongooseModule } from '@nestjs/mongoose';
import { IsIn, IsInt, IsOptional, IsString, Matches, MaxLength, Min } from 'class-validator';
import { Model, Types } from 'mongoose';
import { CurrentUser } from '../../common/decorators/current-user.decorator';
import { JwtAuthGuard } from '../../common/guards/jwt-auth.guard';
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';

@Schema({ timestamps: true, collection: 'transactions' }) class Transaction { @Prop({ type: Types.ObjectId, ref: 'User', required: true, index: true }) userId!: Types.ObjectId; @Prop({ required: true }) date!: Date; @Prop({ required: true, maxlength: 300 }) description!: string; @Prop({ required: true, maxlength: 100 }) category!: string; @Prop({ required: true, min: 0 }) amountCents!: number; @Prop({ enum: ['income', 'expense'], required: true }) type!: string; }
const TransactionSchema = SchemaFactory.createForClass(Transaction); TransactionSchema.index({ userId: 1, date: -1 });
@Schema({ timestamps: true, collection: 'budgets' }) class Budget { @Prop({ type: Types.ObjectId, ref: 'User', required: true, unique: true }) userId!: Types.ObjectId; @Prop({ required: true, min: 0, default: 5000000 }) amountCents!: number; }
const BudgetSchema = SchemaFactory.createForClass(Budget);
class TransactionDto { @IsString() @Matches(/^\d{4}-\d{2}-\d{2}$/) date!: string; @IsString() @MaxLength(300) description!: string; @IsString() @MaxLength(100) category!: string; @IsInt() @Min(0) amountCents!: number; @IsIn(['income', 'expense']) type!: string; }
class BudgetDto { @IsInt() @Min(0) amountCents!: number; }
@Injectable() class ExpensesService { constructor(@InjectModel(Transaction.name) private readonly transactions: Model<Transaction>, @InjectModel(Budget.name) private readonly budgets: Model<Budget>) {} list(userId: string) { return this.transactions.find({ userId }).sort({ date: -1 }).lean().exec(); } create(userId: string, dto: TransactionDto) { return this.transactions.create({ ...dto, date: new Date(`${dto.date}T00:00:00.000Z`), userId }); } update(userId: string, id: string, dto: Partial<TransactionDto>) { const data = dto.date ? { ...dto, date: new Date(`${dto.date}T00:00:00.000Z`) } : dto; return this.transactions.findOneAndUpdate({ _id: id, userId }, data, { new: true, runValidators: true }).exec(); } remove(userId: string, id: string) { return this.transactions.deleteOne({ _id: id, userId }).exec(); } budget(userId: string) { return this.budgets.findOneAndUpdate({ userId }, { $setOnInsert: { amountCents: 5000000 } }, { upsert: true, new: true }).lean().exec(); } saveBudget(userId: string, dto: BudgetDto) { return this.budgets.findOneAndUpdate({ userId }, dto, { upsert: true, new: true, runValidators: true }).lean().exec(); } }
@Controller('expenses') @UseGuards(JwtAuthGuard) class ExpensesController { constructor(private readonly service: ExpensesService) {} @Get('transactions') list(@CurrentUser() user: { sub: string }) { return this.service.list(user.sub); } @Post('transactions') create(@CurrentUser() user: { sub: string }, @Body() dto: TransactionDto) { return this.service.create(user.sub, dto); } @Patch('transactions/:id') update(@CurrentUser() user: { sub: string }, @Param('id') id: string, @Body() dto: Partial<TransactionDto>) { return this.service.update(user.sub, id, dto); } @Delete('transactions/:id') remove(@CurrentUser() user: { sub: string }, @Param('id') id: string) { return this.service.remove(user.sub, id); } @Get('budget') budget(@CurrentUser() user: { sub: string }) { return this.service.budget(user.sub); } @Patch('budget') saveBudget(@CurrentUser() user: { sub: string }, @Body() dto: BudgetDto) { return this.service.saveBudget(user.sub, dto); } }
@Module({ imports: [MongooseModule.forFeature([{ name: Transaction.name, schema: TransactionSchema }, { name: Budget.name, schema: BudgetSchema }])], controllers: [ExpensesController], providers: [ExpensesService] }) export class ExpensesModule {}